// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW5Be-mO8m9XvykwVwxhCtxohTKmUj_zE',
    appId: '1:845922006139:web:0f0b59d3c3a4fd521adede',
    messagingSenderId: '845922006139',
    projectId: 'diora-diabetes',
    authDomain: 'diora-diabetes.firebaseapp.com',
    storageBucket: 'diora-diabetes.firebasestorage.app',
    measurementId: 'G-ZD9F0H1CD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB27mbF-i989bfCack-MEyaEmdavAcuRmI',
    appId: '1:845922006139:android:23f868f00c18b5561adede',
    messagingSenderId: '845922006139',
    projectId: 'diora-diabetes',
    storageBucket: 'diora-diabetes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo_F4jZ2y8bNmzbDxA4sevfrnTNknAwCw',
    appId: '1:845922006139:ios:fc8f0f8a702746941adede',
    messagingSenderId: '845922006139',
    projectId: 'diora-diabetes',
    storageBucket: 'diora-diabetes.firebasestorage.app',
    iosBundleId: 'com.example.dioraDiabetes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo_F4jZ2y8bNmzbDxA4sevfrnTNknAwCw',
    appId: '1:845922006139:ios:fc8f0f8a702746941adede',
    messagingSenderId: '845922006139',
    projectId: 'diora-diabetes',
    storageBucket: 'diora-diabetes.firebasestorage.app',
    iosBundleId: 'com.example.dioraDiabetes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW5Be-mO8m9XvykwVwxhCtxohTKmUj_zE',
    appId: '1:845922006139:web:7a3f7742089e5d4a1adede',
    messagingSenderId: '845922006139',
    projectId: 'diora-diabetes',
    authDomain: 'diora-diabetes.firebaseapp.com',
    storageBucket: 'diora-diabetes.firebasestorage.app',
    measurementId: 'G-JSCX77H07R',
  );
}
